name: Docker CI

on:
  schedule:
    - cron: '30 4 * * *'
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build Docker Image
    uses: ./.github/workflows/docker-build-publish.yaml
    with:
      image: 'smbwebclient'
    secrets: inherit